CPNI: Y/N
CALLER'S FULL NAME:
AEA/REASSURANCE: Y/N
CS AND EDUCATE: Y/N
SALES QUESTION: Y/N
MENTION PHONE : Y/N
SUMMARIZE DUE DATE & AMT : Y/N
DISPOSITION CALL : Y/N
ASK FOR EMAIL ADDR : Y/N
SERVICE CHECK ?? 
