$$$$ - SEASONAL MACRO - $$$$
* CPNI : Y/N
* CALLER'S FULL NAME : JOHN SMITH
* ADD/REM SEASONAL : ADD/REM
* QUALIFIED FOR SEASONAL? : Y/N
* SEASONAL DURATION : 6MO
* SEASONAL START DATE: 11/11/11
* SEASONAL END DATE : 11/11/11
* REGULAR MONTHLY RATE : $10
* SEASONAL MONTHLY RATE : $45
* NEXT QUALIFIED SEASONAL HOLD: 11/11/11
* FORWARDING ADDRESS: Y/N
* REASON FOR SEASONAL HOLD/REM: 
* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
